#!/usr/bin/env python3
import sys
import time
from mutagen.mp4 import MP4
for file in sys.argv[1:]:
    print(f"File: \"{file}\".")
    tags = MP4(file)
    value = tags["\xa9cmt"]
    # print(value)
    if value and value[0] and 'http' not in value[0]: # if list is non-empty, if
        # string is non-empty, and if http not in string
        print("Fixing comment metadata.")
        tags["\xa9cmt"] = [""] # empty comment
        tags.save() # don't need to re-supply with path
