#!/bin/bash
# First check the python packages are installed
dependencies=(mutagen musicbrainzngs discogs_client bs4 PIL unidecode pandas)
for dependency in ${dependencies[@]}; do
  printf "Checking for dependency $dependency... "
  if python3 -c "import $dependency" 2>/dev/null; then
    echo "package already installed."
  else
    echo "installing $dependency..."
    pip install $dependency
  fi
done
# Next create a "config" file if it does not exist already
[ ! -e config ] && touch config
