#!/bin/bash
# Places symlinks to these functions inside home directory
# Only remove existing files if they are symlinks; don't overwrite real data
if [ -L ~/metadata ]; then
  rm ~/metadata
fi
if [ -L ~/youtube ]; then
  rm ~/youtube
fi
if hash realpath 2>/dev/null; # on my macOS is available
  ln -s $(realpath ./metadata) ~/metadata
  ln -s $(realpath ./youtube) ~/youtube
else # on all Linux distros is available; mac has it but no -f option
  ln -s $(readlink -f ./metadata) ~/metadata
  ln -s $(readlink -f ./youtube) ~/youtube
fi
