#!/bin/bash
# Places symlinks to these functions inside home directory
# Only remove existing files if they are symlinks; don't overwrite real data
# Symlinks will be *relative* to home directory
for exe in metadata youtube commentfix; do
  echo "Creating symlink for \"$exe\"..."
  [ -L ~/$exe ] && rm ~/$exe
  ln -s youtubetag/$exe ~/$exe
done
# if hash realpath 2>/dev/null; then # on my macOS is available
#   ln -s $(realpath ./$exe) ~/$exe
# else # on all Linux distros is available; mac has it but no -f option
#   ln -s $(readlink -f ./$exe) ~/$exe
# fi
