#!/bin/bash

# Download directory; default is where I keep my music
directory="~/Google\ Drive/Playlist"

# Initial stuff
directory="${directory/"~"/$HOME}" # don't expand spaces, but expand ~
name="${@:2}" # select all args (@) from 2 to end
url="$1" # the original URL
if [ -z "$url" ]; then
  echo "ERROR: Must supply URL."
  exit 1
fi
if [ -z "$name" ]; then
  echo "ERROR: Must supply output filename."
  exit 1
fi

# Download, using youtube-dl
path="$directory/$name.m4a" # the filename
if [ -f "$path" ]; then # must remove any old download, or get errors with youtube-dl
  echo "Removing old file..."
  rm "$path"
fi
echo "Downloading $url into filename: $name"
youtube-dl -f bestaudio[ext=m4a] --no-playlist --prefer-ffmpeg "$url" -o "$path" # no playlist, in case user provides playlist URL
# youtube-dl -f bestaudio[ext=m4a] --no-playlist --prefer-ffmpeg --embed-thumbnail "$url" -o "$path"
# youtube-dl -f bestaudio[ext=m4a] -t "$name" --metadata-from-title "%(artist)s - %(title)s" --no-playlist --prefer-ffmpeg --embed-thumbnail "$url" -o "$path"

# Normalize audio and re-compress into AAC
echo "Normalizing volume to -26dB."
ffmpeg-normalize -uf -a aac "$path"
  # -a specifies audiocodec; see help info, this is wav file (ideal sense we don't want to recompress the raw data)
mv "$directory/normalized-$name.m4a" "$path"

# Normalize output and get raw WAV data (much more space)
# ffmpeg-normalize "$directory/$name.m4a"
# mv "$directory/normalized-$name.wav" "$directory/$name.wav"
# rm "$path"

# Change metadata using python function
metadata --noconfirmalbum "$url" "$path"

